// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MindScorePlatform.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MindScorePlatform.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260418172406_AddCareerFitAssessment")]
    partial class AddCareerFitAssessment
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MindScorePlatform.Domain.Entities.AgeBand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("displayorder");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("isactive");

                    b.Property<int>("MaxAge")
                        .HasColumnType("integer")
                        .HasColumnName("maxage");

                    b.Property<int>("MinAge")
                        .HasColumnType("integer")
                        .HasColumnName("minage");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("agebands", (string)null);
                });

            modelBuilder.Entity("MindScorePlatform.Domain.Entities.AgeBandModuleWeight", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AgeBandId")
                        .HasColumnType("uuid")
                        .HasColumnName("agebandid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<Guid>("ModuleId")
                        .HasColumnType("uuid")
                        .HasColumnName("moduleid");

                    b.Property<double>("Weight")
                        .HasColumnType("double precision")
                        .HasColumnName("weight");

                    b.HasKey("Id");

                    b.HasIndex("AgeBandId");

                    b.HasIndex("ModuleId");

                    b.ToTable("agebandmoduleweights", (string)null);
                });

            modelBuilder.Entity("MindScorePlatform.Domain.Entities.Module", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("displayorder");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("isactive");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("modules", (string)null);
                });

            modelBuilder.Entity("MindScorePlatform.Domain.Entities.ModuleScore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<Guid>("ModuleId")
                        .HasColumnType("uuid")
                        .HasColumnName("moduleid");

                    b.Property<decimal>("Percentile")
                        .HasColumnType("numeric")
                        .HasColumnName("percentile");

                    b.Property<decimal>("RawScore")
                        .HasColumnType("numeric")
                        .HasColumnName("rawscore");

                    b.Property<Guid>("TestId")
                        .HasColumnType("uuid")
                        .HasColumnName("testid");

                    b.Property<decimal>("WeightedScore")
                        .HasColumnType("numeric")
                        .HasColumnName("weightedscore");

                    b.HasKey("Id");

                    b.HasIndex("ModuleId");

                    b.ToTable("modulescores", (string)null);
                });

            modelBuilder.Entity("MindScorePlatform.Domain.Entities.NormReference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AgeBandId")
                        .HasColumnType("uuid")
                        .HasColumnName("agebandid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<double>("Mean")
                        .HasColumnType("double precision")
                        .HasColumnName("mean");

                    b.Property<Guid>("ModuleId")
                        .HasColumnType("uuid")
                        .HasColumnName("moduleid");

                    b.Property<int>("SampleSize")
                        .HasColumnType("integer")
                        .HasColumnName("samplesize");

                    b.Property<double>("StandardDeviation")
                        .HasColumnType("double precision")
                        .HasColumnName("standarddeviation");

                    b.HasKey("Id");

                    b.HasIndex("AgeBandId");

                    b.HasIndex("ModuleId");

                    b.ToTable("normreferences", (string)null);
                });

            modelBuilder.Entity("MindScorePlatform.Domain.Entities.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AgeBandId")
                        .HasColumnType("uuid")
                        .HasColumnName("agebandid");

                    b.Property<string>("BranchingRulesJson")
                        .HasColumnType("text")
                        .HasColumnName("branchingrulesjson");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<string>("ContextTagsJson")
                        .HasColumnType("text")
                        .HasColumnName("contexttagsjson");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdatutc");

                    b.Property<string>("Difficulty")
                        .HasColumnType("text")
                        .HasColumnName("difficulty");

                    b.Property<bool?>("IsReverseScored")
                        .HasColumnType("boolean")
                        .HasColumnName("isreversescored");

                    b.Property<Guid?>("ModuleId")
                        .HasColumnType("uuid")
                        .HasColumnName("moduleid");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("orderid");

                    b.Property<int>("QuestionType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("questiontype");

                    b.Property<string>("ScenarioOptionsJson")
                        .HasColumnType("text")
                        .HasColumnName("scenariooptionsjson");

                    b.Property<Guid>("TestId")
                        .HasColumnType("uuid")
                        .HasColumnName("testid");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.Property<int?>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("numeric")
                        .HasColumnName("weight");

                    b.HasKey("Id");

                    b.HasIndex("AgeBandId");

                    b.HasIndex("ModuleId");

                    b.HasIndex("TestId", "Code")
                        .IsUnique()
                        .HasDatabaseName("IX_Questions_TestId_Code");

                    b.HasIndex("TestId", "Order")
                        .IsUnique()
                        .HasDatabaseName("IX_Questions_TestId_Order");

                    b.ToTable("questions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000001"),
                            Code = "EI_01",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Order = 1,
                            QuestionType = 0,
                            TestId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Text = "I feel energised after spending time with friends or a group of people."
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000002"),
                            Code = "EI_02_R",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsReverseScored = true,
                            Order = 2,
                            QuestionType = 0,
                            TestId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Text = "After a busy social day, I need quiet time alone to feel like myself again."
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000003"),
                            Code = "EI_03",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Order = 3,
                            QuestionType = 0,
                            TestId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Text = "I enjoy starting conversations with people I've never met before."
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000004"),
                            Code = "EI_04_R",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsReverseScored = true,
                            Order = 4,
                            QuestionType = 0,
                            TestId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Text = "I find large gatherings draining, even when I enjoy the people there."
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000005"),
                            BranchingRulesJson = "{\"conditions\":[{\"answerRange\":[1,2],\"nextQuestionCode\":\"EI_DEEP_R\"},{\"answerRange\":[4,5],\"nextQuestionCode\":\"EI_DEEP_E\"}]}",
                            Code = "EI_05",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Order = 5,
                            QuestionType = 0,
                            TestId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Text = "I think better when I'm talking ideas through with someone rather than sitting with them alone."
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000006"),
                            Code = "SN_01",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Order = 6,
                            QuestionType = 0,
                            TestId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Text = "I prefer clear, step-by-step instructions over figuring things out as I go."
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000007"),
                            Code = "SN_02_R",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsReverseScored = true,
                            Order = 7,
                            QuestionType = 0,
                            TestId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Text = "I often find myself thinking about what could be, more than what currently is."
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000008"),
                            Code = "SN_03",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Order = 8,
                            QuestionType = 0,
                            TestId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Text = "I trust facts and direct experience more than gut feelings or hunches."
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000009"),
                            Code = "SN_04_R",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsReverseScored = true,
                            Order = 9,
                            QuestionType = 0,
                            TestId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Text = "I get excited by new ideas and possibilities, even when they're not fully formed yet."
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000010"),
                            Code = "SN_05",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Order = 10,
                            QuestionType = 0,
                            TestId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Text = "I focus on the task at hand rather than getting distracted by future possibilities."
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000011"),
                            Code = "TF_01",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Order = 11,
                            QuestionType = 0,
                            TestId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Text = "When solving a problem, I focus on what's logical and objective rather than what feels right."
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000012"),
                            Code = "TF_02_R",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsReverseScored = true,
                            Order = 12,
                            QuestionType = 0,
                            TestId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Text = "I find it difficult to make a decision if I know it will upset someone close to me."
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000013"),
                            Code = "TF_03",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Order = 13,
                            QuestionType = 0,
                            TestId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Text = "I believe being fair and consistent matters more than making exceptions for individuals."
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000014"),
                            Code = "TF_04_R",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsReverseScored = true,
                            Order = 14,
                            QuestionType = 0,
                            TestId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Text = "I consider how my decisions will affect the feelings of the people involved."
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000015"),
                            BranchingRulesJson = "{\"conditions\":[{\"answerRange\":[1,2],\"nextQuestionCode\":\"TF_DEEP_V\"},{\"answerRange\":[4,5],\"nextQuestionCode\":\"TF_DEEP_L\"}]}",
                            Code = "TF_05",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Order = 15,
                            QuestionType = 0,
                            TestId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Text = "I prefer a well-reasoned argument over an emotional appeal when making up my mind."
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000016"),
                            Code = "JP_01",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Order = 16,
                            QuestionType = 0,
                            TestId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Text = "I like having a clear plan before I start a task."
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000017"),
                            Code = "JP_02_R",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsReverseScored = true,
                            Order = 17,
                            QuestionType = 0,
                            TestId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Text = "I prefer to keep my options open rather than committing to a fixed plan."
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000018"),
                            Code = "JP_03",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Order = 18,
                            QuestionType = 0,
                            TestId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Text = "I feel unsettled when plans change unexpectedly at the last minute."
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000019"),
                            Code = "JP_04_R",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsReverseScored = true,
                            Order = 19,
                            QuestionType = 0,
                            TestId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Text = "I often decide things at the last moment and feel perfectly comfortable doing so."
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000020"),
                            Code = "JP_05",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Order = 20,
                            QuestionType = 0,
                            TestId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Text = "I prefer to have things resolved and settled rather than leaving them open-ended."
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000001"),
                            Code = "EI_DEEP_E",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsReverseScored = false,
                            Order = 500,
                            QuestionType = 0,
                            TestId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Text = "When I need to recharge, I gravitate toward busy social events rather than spending time alone."
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000002"),
                            Code = "EI_DEEP_R",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsReverseScored = true,
                            Order = 501,
                            QuestionType = 0,
                            TestId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Text = "Extended periods of solitude feel essential to my wellbeing, even when life is going well."
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000003"),
                            Code = "TF_DEEP_L",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsReverseScored = false,
                            Order = 502,
                            QuestionType = 0,
                            TestId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Text = "When solving problems, I focus on root causes and system efficiency rather than who is affected."
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000004"),
                            Code = "TF_DEEP_V",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsReverseScored = true,
                            Order = 503,
                            QuestionType = 0,
                            TestId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Text = "The emotional impact of a decision on others weighs more heavily on me than its logical merits."
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000005"),
                            Code = "EI_CAR_01",
                            ContextTagsJson = "[\"Career\"]",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsReverseScored = false,
                            Order = 21,
                            QuestionType = 0,
                            TestId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Text = "Collaborative brainstorming sessions at work leave me more energized than focused solo work."
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000006"),
                            Code = "SN_CAR_01_R",
                            ContextTagsJson = "[\"Career\"]",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsReverseScored = true,
                            Order = 22,
                            QuestionType = 0,
                            TestId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Text = "I often find myself pitching future possibilities at work rather than refining existing processes."
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000007"),
                            Code = "TF_CAR_01_R",
                            ContextTagsJson = "[\"Career\"]",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsReverseScored = true,
                            Order = 23,
                            QuestionType = 0,
                            TestId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Text = "When workplace decisions affect team morale, I weight personal impact over operational logic."
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000008"),
                            Code = "JP_CAR_01",
                            ContextTagsJson = "[\"Career\"]",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsReverseScored = false,
                            Order = 24,
                            QuestionType = 0,
                            TestId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Text = "I plan my workweek in detail and resist changes to my scheduled priorities."
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000009"),
                            Code = "SCEN_CAR_01",
                            ContextTagsJson = "[\"Career\"]",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Order = 25,
                            QuestionType = 1,
                            ScenarioOptionsJson = "[{\"text\":\"Call a working meeting first thing, gather everyone's views aloud, and push the group toward a shared direction through open discussion.\",\"traitMappings\":{\"EnergySource\":5,\"LifeApproach\":4}},{\"text\":\"Research how similar teams solved comparable problems, gather concrete data, and draft a detailed proposal based on what has worked before.\",\"traitMappings\":{\"PerceptionMode\":5,\"LifeApproach\":4}},{\"text\":\"Spend time alone thinking through emerging patterns, then share a conceptual framework exploring possibilities the team may not have considered yet.\",\"traitMappings\":{\"EnergySource\":2,\"PerceptionMode\":1}},{\"text\":\"Check in individually with teammates to understand how each is affected, then propose an approach balancing the group's emotional and practical needs.\",\"traitMappings\":{\"DecisionStyle\":1,\"EnergySource\":3}}]",
                            TestId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Text = "Your team has been asked to recommend a new approach for an ongoing project, but the brief is vague and stakeholders disagree on priorities. You have one week before presenting a proposal, and your manager has delegated the decision to the team. How do you most naturally engage with this situation?"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000010"),
                            Code = "SCEN_CAR_02",
                            ContextTagsJson = "[\"Career\"]",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Order = 26,
                            QuestionType = 1,
                            ScenarioOptionsJson = "[{\"text\":\"Build a detailed hour-by-hour schedule that protects the non-negotiable deadlines first, then scope down the lower-impact project to fit within remaining hours.\",\"traitMappings\":{\"LifeApproach\":5,\"DecisionStyle\":4}},{\"text\":\"Talk it through with both project stakeholders to understand what each needs emotionally, then propose a middle path everyone can accept.\",\"traitMappings\":{\"DecisionStyle\":1,\"EnergySource\":4}},{\"text\":\"Keep both options open and adapt day by day, trusting I can shift attention as each project's actual urgency becomes clearer.\",\"traitMappings\":{\"LifeApproach\":1,\"PerceptionMode\":2}},{\"text\":\"Map the underlying system — who needs what, by when, and why — then make the most logically efficient cut even if it disappoints someone.\",\"traitMappings\":{\"DecisionStyle\":5,\"PerceptionMode\":4}}]",
                            TestId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Text = "Two important projects are due the same week and you cannot fully deliver both to your usual standard. Your manager leaves the trade-off to you, and neither project has an obvious priority. You have a full day before you need to commit to a plan. What is your most likely response?"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000011"),
                            Code = "EI_REL_01",
                            ContextTagsJson = "[\"Relationships\"]",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsReverseScored = false,
                            Order = 30,
                            QuestionType = 0,
                            TestId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Text = "I stay energized after long social gatherings with close friends, even when they run late."
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000012"),
                            Code = "SN_REL_01_R",
                            ContextTagsJson = "[\"Relationships\"]",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsReverseScored = true,
                            Order = 31,
                            QuestionType = 0,
                            TestId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Text = "I often sense unspoken meanings in a partner's words before I notice the literal facts."
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000013"),
                            Code = "TF_REL_01",
                            ContextTagsJson = "[\"Relationships\"]",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsReverseScored = false,
                            Order = 32,
                            QuestionType = 0,
                            TestId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Text = "During relationship conflicts, I focus on identifying what is objectively fair rather than comforting feelings first."
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000014"),
                            Code = "JP_REL_01_R",
                            ContextTagsJson = "[\"Relationships\"]",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsReverseScored = true,
                            Order = 33,
                            QuestionType = 0,
                            TestId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Text = "I prefer spontaneous plans with close people over keeping fixed routines or scheduled commitments."
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000015"),
                            Code = "SCEN_REL_01",
                            ContextTagsJson = "[\"Relationships\"]",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Order = 34,
                            QuestionType = 1,
                            ScenarioOptionsJson = "[{\"text\":\"Suggest meeting in person to talk it through openly — you process through conversation and would rather hash it out than sit with uncertainty.\",\"traitMappings\":{\"EnergySource\":5,\"LifeApproach\":4}},{\"text\":\"Sit with the situation for several days, noticing patterns in their behaviour and replaying past interactions before deciding how to respond.\",\"traitMappings\":{\"EnergySource\":1,\"PerceptionMode\":4}},{\"text\":\"Focus on what you can logically observe — their actions, not assumed intent — and wait for concrete information before investing emotional energy.\",\"traitMappings\":{\"DecisionStyle\":5,\"PerceptionMode\":4}},{\"text\":\"Send a warm, open message acknowledging you sense something is off and making space for whatever they need to share.\",\"traitMappings\":{\"DecisionStyle\":1,\"EnergySource\":3}}]",
                            TestId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Text = "A close friend has grown distant over the past month, cancelling plans and giving short replies. You do not know the cause, and when you last asked, they deflected. You are starting to feel hurt and uncertain whether to press further. What do you most likely do next?"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000016"),
                            Code = "SCEN_REL_02",
                            ContextTagsJson = "[\"Relationships\"]",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Order = 35,
                            QuestionType = 1,
                            ScenarioOptionsJson = "[{\"text\":\"Work through a written pros-and-cons analysis covering finances, career trajectories, and logistics — decide based on which option objectively maximizes combined outcomes.\",\"traitMappings\":{\"DecisionStyle\":5,\"LifeApproach\":4}},{\"text\":\"Have a long, feelings-first conversation — what it means for each of you, what fears are surfacing — and let the emotional truth lead.\",\"traitMappings\":{\"DecisionStyle\":1,\"EnergySource\":4}},{\"text\":\"Hold off committing either way, stay open, and see what new information or intuition emerges over the next couple of weeks.\",\"traitMappings\":{\"LifeApproach\":1,\"PerceptionMode\":2}},{\"text\":\"Take time alone to imagine both futures vividly, then share the deeper patterns and possibilities you noticed before deciding together.\",\"traitMappings\":{\"EnergySource\":1,\"PerceptionMode\":1}}]",
                            TestId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Text = "Your partner has been offered a career opportunity that would require you both to relocate within three months. The move is exciting for them but disruptive for your own career and social life. A decision is needed this weekend. How do you most naturally engage?"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000017"),
                            Code = "EI_LEA_01",
                            ContextTagsJson = "[\"Leadership\"]",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsReverseScored = false,
                            Order = 40,
                            QuestionType = 0,
                            TestId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Text = "As a leader, I prefer visible front-line roles that involve speaking to large groups and rallying people."
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000018"),
                            Code = "SN_LEA_01",
                            ContextTagsJson = "[\"Leadership\"]",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsReverseScored = false,
                            Order = 41,
                            QuestionType = 0,
                            TestId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Text = "When leading, I rely on concrete performance data and track records rather than long-term vision statements."
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000019"),
                            Code = "TF_LEA_01_R",
                            ContextTagsJson = "[\"Leadership\"]",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsReverseScored = true,
                            Order = 42,
                            QuestionType = 0,
                            TestId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Text = "When leading, I weigh each team member's personal circumstances more heavily than strict performance standards."
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000020"),
                            Code = "JP_LEA_01",
                            ContextTagsJson = "[\"Leadership\"]",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsReverseScored = false,
                            Order = 43,
                            QuestionType = 0,
                            TestId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Text = "I set clear goals, milestones, and deadlines for my team and hold people firmly to them."
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000021"),
                            Code = "SCEN_LEA_01",
                            ContextTagsJson = "[\"Leadership\"]",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Order = 44,
                            QuestionType = 1,
                            ScenarioOptionsJson = "[{\"text\":\"Schedule a direct one-on-one this week, lay out the performance facts clearly, and agree on measurable expectations with firm deadlines.\",\"traitMappings\":{\"DecisionStyle\":5,\"LifeApproach\":5}},{\"text\":\"Create space for an open conversation focused on how they are doing as a person — something is likely going on beneath the surface.\",\"traitMappings\":{\"DecisionStyle\":1,\"EnergySource\":4}},{\"text\":\"Observe quietly for another week, gather more data points and context from others, then decide once the pattern is clearer.\",\"traitMappings\":{\"EnergySource\":2,\"PerceptionMode\":4}},{\"text\":\"Hold a team discussion about workload and shared standards, letting the group itself shape how to address the drift.\",\"traitMappings\":{\"EnergySource\":5,\"LifeApproach\":3}}]",
                            TestId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Text = "A previously high-performing team member has missed three consecutive deadlines and is withdrawing in meetings. Other teammates are starting to pick up the slack and grumble quietly. You have not yet spoken directly with the person, and a quarterly review is two weeks away. How do you proceed?"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000022"),
                            Code = "SCEN_LEA_02",
                            ContextTagsJson = "[\"Leadership\"]",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Order = 45,
                            QuestionType = 1,
                            ScenarioOptionsJson = "[{\"text\":\"Convene a cross-functional working group, debate both options openly in a full-day session, and push toward a shared decision through rapid group dialogue.\",\"traitMappings\":{\"EnergySource\":5,\"LifeApproach\":4}},{\"text\":\"Commission a deep dive into historical data and comparable cases, then recommend the option the evidence most concretely supports.\",\"traitMappings\":{\"PerceptionMode\":5,\"DecisionStyle\":4}},{\"text\":\"Pick the unfamiliar opportunity — the pattern feels right, the upside matters, and waiting for full certainty will cost momentum.\",\"traitMappings\":{\"PerceptionMode\":1,\"LifeApproach\":2}},{\"text\":\"Consider how each option affects the team's wellbeing and growth, and pick the one people can believe in and commit to.\",\"traitMappings\":{\"DecisionStyle\":1,\"EnergySource\":3}}]",
                            TestId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Text = "Your team must choose between two strategic directions for the next quarter, each with incomplete information. One is a proven safe bet with modest gains; the other is an unfamiliar opportunity with bigger potential upside and real risk. A recommendation is due by Friday. How do you approach the choice?"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000023"),
                            Code = "EI_PD_01_R",
                            ContextTagsJson = "[\"PersonalDevelopment\"]",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsReverseScored = true,
                            Order = 50,
                            QuestionType = 0,
                            TestId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Text = "My most meaningful personal growth happens during extended solitude rather than in groups or conversations."
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000024"),
                            Code = "SN_PD_01",
                            ContextTagsJson = "[\"PersonalDevelopment\"]",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsReverseScored = false,
                            Order = 51,
                            QuestionType = 0,
                            TestId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Text = "I prefer tracking concrete habits and measurable progress over exploring abstract themes about who I am becoming."
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000025"),
                            Code = "TF_PD_01",
                            ContextTagsJson = "[\"PersonalDevelopment\"]",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsReverseScored = false,
                            Order = 52,
                            QuestionType = 0,
                            TestId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Text = "When reflecting on myself, I diagnose what is inefficient or irrational rather than sitting with emotions first."
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000026"),
                            Code = "JP_PD_01_R",
                            ContextTagsJson = "[\"PersonalDevelopment\"]",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsReverseScored = true,
                            Order = 53,
                            QuestionType = 0,
                            TestId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Text = "I let my personal growth unfold organically rather than committing to structured routines or plans."
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000027"),
                            Code = "SCEN_PD_01",
                            ContextTagsJson = "[\"PersonalDevelopment\"]",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Order = 54,
                            QuestionType = 1,
                            ScenarioOptionsJson = "[{\"text\":\"Journal alone for hours, mapping connections between current behaviours and deeper themes you have been noticing over the past months.\",\"traitMappings\":{\"EnergySource\":1,\"PerceptionMode\":1}},{\"text\":\"Reach out to a trusted friend or coach, talk it through aloud, and let the conversation surface what you could not see alone.\",\"traitMappings\":{\"EnergySource\":5,\"DecisionStyle\":2}},{\"text\":\"Build a structured weekend plan — specific reading, specific exercises, specific reflection prompts — and work through it step by step.\",\"traitMappings\":{\"LifeApproach\":5,\"DecisionStyle\":4}},{\"text\":\"Research proven frameworks for this kind of pattern, identify the mechanism causing it, and design a logical intervention to test.\",\"traitMappings\":{\"DecisionStyle\":5,\"PerceptionMode\":4}}]",
                            TestId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Text = "You have been feeling stuck in a recurring personal pattern — one that surfaces in work, relationships, and your own self-talk. You have noticed it clearly this week and know you want to address it. You have a free weekend ahead to work on it. What do you most naturally reach for?"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000028"),
                            Code = "SCEN_PD_02",
                            ContextTagsJson = "[\"PersonalDevelopment\"]",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Order = 55,
                            QuestionType = 1,
                            ScenarioOptionsJson = "[{\"text\":\"Write a detailed weekly plan with specific times, metrics, and milestones, then commit publicly to maintain accountability through clear structure.\",\"traitMappings\":{\"LifeApproach\":5,\"DecisionStyle\":4}},{\"text\":\"Start loosely, see what feels right in practice, and adapt the approach as you go without committing to a rigid plan.\",\"traitMappings\":{\"LifeApproach\":1,\"PerceptionMode\":2}},{\"text\":\"Research behaviour-change science, identify the mechanisms most likely to work for someone like you, and design a system based on evidence.\",\"traitMappings\":{\"PerceptionMode\":5,\"DecisionStyle\":5}},{\"text\":\"Involve close friends or a group — shared energy, public commitment, and social reinforcement are what actually make things stick for you.\",\"traitMappings\":{\"EnergySource\":5,\"DecisionStyle\":2}}]",
                            TestId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Text = "You have decided to make a significant lifestyle change — a new sleep schedule, exercise routine, and reading practice — starting next month. You have three weeks to prepare. You know from experience that some change strategies work better for you than others. How do you set yourself up?"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000001"),
                            Code = "CF_01",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Order = 1,
                            QuestionType = 1,
                            ScenarioOptionsJson = "[{\"text\":\"Building something concrete \\u2014 a product, system, or solution that works.\",\"clusterImpact\":{\"BUILDER\":5,\"OPERATOR\":2}},{\"text\":\"Digging into data and uncovering insights that inform strategy.\",\"clusterImpact\":{\"ANALYST\":5,\"OPERATOR\":2}},{\"text\":\"Leading people toward a shared goal and watching them grow.\",\"clusterImpact\":{\"LEADER\":5,\"COMMUNICATOR\":2}},{\"text\":\"Creating something original that changes how people feel or think.\",\"clusterImpact\":{\"CREATOR\":5,\"ENTREPRENEUR\":2}}]",
                            TestId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Text = "Your ideal work setup energises you most when you are..."
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000002"),
                            Code = "CF_02",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Order = 2,
                            QuestionType = 1,
                            ScenarioOptionsJson = "[{\"text\":\"Dive in, experiment, and iterate fast.\",\"clusterImpact\":{\"ENTREPRENEUR\":5,\"BUILDER\":3}},{\"text\":\"Research thoroughly before committing to a direction.\",\"clusterImpact\":{\"ANALYST\":5,\"OPERATOR\":3}},{\"text\":\"Rally the team and divide responsibilities across people.\",\"clusterImpact\":{\"LEADER\":5,\"COMMUNICATOR\":3}},{\"text\":\"Consider carefully how it will affect the people involved.\",\"clusterImpact\":{\"CAREGIVER\":5,\"COMMUNICATOR\":2}}]",
                            TestId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Text = "When a brand-new challenge lands on your desk, your first instinct is to..."
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000003"),
                            Code = "CF_03",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Order = 3,
                            QuestionType = 1,
                            ScenarioOptionsJson = "[{\"text\":\"Shipping a product or system that millions of people rely on every day.\",\"clusterImpact\":{\"BUILDER\":5,\"OPERATOR\":2}},{\"text\":\"Discovering an insight that completely changed a strategy or market.\",\"clusterImpact\":{\"ANALYST\":5,\"ENTREPRENEUR\":3}},{\"text\":\"Watching someone you mentored become a leader in their own right.\",\"clusterImpact\":{\"CAREGIVER\":5,\"LEADER\":4}},{\"text\":\"Creating a piece of work that shifted culture or moved public opinion.\",\"clusterImpact\":{\"CREATOR\":5,\"COMMUNICATOR\":3}}]",
                            TestId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Text = "The achievement that would make you most proud is..."
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000004"),
                            Code = "CF_04",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Order = 4,
                            QuestionType = 1,
                            ScenarioOptionsJson = "[{\"text\":\"Built, shipped, or fixed something real and tangible.\",\"clusterImpact\":{\"BUILDER\":5,\"OPERATOR\":2}},{\"text\":\"Solved a complex puzzle or learned something genuinely unexpected.\",\"clusterImpact\":{\"ANALYST\":5,\"CREATOR\":2}},{\"text\":\"Helped someone navigate a genuinely difficult situation.\",\"clusterImpact\":{\"CAREGIVER\":5,\"COMMUNICATOR\":3}},{\"text\":\"Inspired a room, closed a deal, or led a high-stakes conversation.\",\"clusterImpact\":{\"COMMUNICATOR\":5,\"LEADER\":3}}]",
                            TestId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Text = "At the end of a great workday, you feel best when you have..."
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000005"),
                            Code = "CF_05",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Order = 5,
                            QuestionType = 1,
                            ScenarioOptionsJson = "[{\"text\":\"Engineer a technical workaround or a creative patch.\",\"clusterImpact\":{\"BUILDER\":5,\"ANALYST\":3}},{\"text\":\"Step up, make a call, and rally everyone forward.\",\"clusterImpact\":{\"LEADER\":5,\"ENTREPRENEUR\":4}},{\"text\":\"Uncover the human issue that is really blocking progress.\",\"clusterImpact\":{\"CAREGIVER\":5,\"COMMUNICATOR\":3}},{\"text\":\"Throw out the old plan and reimagine the approach entirely.\",\"clusterImpact\":{\"CREATOR\":5,\"ENTREPRENEUR\":3}}]",
                            TestId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Text = "When your team hits a serious roadblock, you tend to..."
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000006"),
                            Code = "CF_06",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Order = 6,
                            QuestionType = 1,
                            ScenarioOptionsJson = "[{\"text\":\"Trust the data \\u2014 you build models and pressure-test options first.\",\"clusterImpact\":{\"ANALYST\":5,\"OPERATOR\":3}},{\"text\":\"Trust your gut and move before the picture is fully clear.\",\"clusterImpact\":{\"ENTREPRENEUR\":5,\"CREATOR\":3}},{\"text\":\"Build consensus \\u2014 a decision everyone owns beats a perfect top-down call.\",\"clusterImpact\":{\"LEADER\":5,\"CAREGIVER\":3}},{\"text\":\"Filter through values \\u2014 what is right, not just what is optimal.\",\"clusterImpact\":{\"CAREGIVER\":5,\"COMMUNICATOR\":2}}]",
                            TestId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Text = "When it comes to making important decisions, you typically..."
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000007"),
                            Code = "CF_07",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Order = 7,
                            QuestionType = 1,
                            ScenarioOptionsJson = "[{\"text\":\"Designing and building a complex technical system from scratch.\",\"clusterImpact\":{\"BUILDER\":5,\"ANALYST\":3}},{\"text\":\"Launching a brand-new business or product from zero to market.\",\"clusterImpact\":{\"ENTREPRENEUR\":5,\"CREATOR\":3}},{\"text\":\"Coaching a high-potential team to peak performance.\",\"clusterImpact\":{\"LEADER\":5,\"CAREGIVER\":4}},{\"text\":\"Creating a product experience that genuinely delights people.\",\"clusterImpact\":{\"CREATOR\":5,\"BUILDER\":3}}]",
                            TestId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Text = "If you could pick your next project, your dream would be..."
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000008"),
                            Code = "CF_08",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Order = 8,
                            QuestionType = 1,
                            ScenarioOptionsJson = "[{\"text\":\"Follow structured plans and resist unscheduled interruptions.\",\"clusterImpact\":{\"OPERATOR\":5,\"ANALYST\":3}},{\"text\":\"Stay fluid and re-prioritise constantly based on what matters most right now.\",\"clusterImpact\":{\"ENTREPRENEUR\":5,\"LEADER\":3}},{\"text\":\"Block long stretches for deep, uninterrupted thinking.\",\"clusterImpact\":{\"ANALYST\":5,\"BUILDER\":4}},{\"text\":\"Leave room for spontaneous collaboration and idea exchange.\",\"clusterImpact\":{\"COMMUNICATOR\":5,\"CREATOR\":3}}]",
                            TestId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Text = "When managing your time and workflow, you..."
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000009"),
                            Code = "CF_09",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Order = 9,
                            QuestionType = 1,
                            ScenarioOptionsJson = "[{\"text\":\"Diagnose the root cause systematically before touching anything.\",\"clusterImpact\":{\"ANALYST\":5,\"BUILDER\":3}},{\"text\":\"Build a fix fast and put safeguards in place to prevent recurrence.\",\"clusterImpact\":{\"BUILDER\":5,\"OPERATOR\":4}},{\"text\":\"Coordinate the response \\u2014 communicate, assign roles, manage stakeholders.\",\"clusterImpact\":{\"LEADER\":5,\"COMMUNICATOR\":3}},{\"text\":\"Focus first on the people impacted and how to make things right for them.\",\"clusterImpact\":{\"CAREGIVER\":5,\"COMMUNICATOR\":3}}]",
                            TestId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Text = "When something fails or breaks badly at work, you..."
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000010"),
                            Code = "CF_10",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Order = 10,
                            QuestionType = 1,
                            ScenarioOptionsJson = "[{\"text\":\"Infrastructure or systems that scale and outlast their creator.\",\"clusterImpact\":{\"BUILDER\":5,\"OPERATOR\":3}},{\"text\":\"Revenue growth, market leadership, or a thriving business.\",\"clusterImpact\":{\"ENTREPRENEUR\":5,\"ANALYST\":2}},{\"text\":\"Improving someone\\u0027s health, confidence, or life trajectory.\",\"clusterImpact\":{\"CAREGIVER\":5,\"COMMUNICATOR\":3}},{\"text\":\"Shifting how people think, feel, or experience the world around them.\",\"clusterImpact\":{\"CREATOR\":5,\"COMMUNICATOR\":4}}]",
                            TestId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Text = "The type of impact you care most about creating is..."
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000011"),
                            Code = "CF_11",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Order = 11,
                            QuestionType = 1,
                            ScenarioOptionsJson = "[{\"text\":\"Study documentation, research, and theory before taking action.\",\"clusterImpact\":{\"ANALYST\":5,\"OPERATOR\":3}},{\"text\":\"Jump in and learn entirely by doing \\u2014 mistakes included.\",\"clusterImpact\":{\"BUILDER\":5,\"ENTREPRENEUR\":4}},{\"text\":\"Watch an expert do it, then teach it to someone else to lock it in.\",\"clusterImpact\":{\"COMMUNICATOR\":5,\"LEADER\":3}},{\"text\":\"Learn alongside a mentor who gives real-time personalised feedback.\",\"clusterImpact\":{\"CAREGIVER\":3,\"LEADER\":3,\"COMMUNICATOR\":4}}]",
                            TestId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Text = "When learning something completely new, you prefer to..."
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000012"),
                            Code = "CF_12",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Order = 12,
                            QuestionType = 1,
                            ScenarioOptionsJson = "[{\"text\":\"Map out a clear plan with milestones, owners, and dependencies.\",\"clusterImpact\":{\"OPERATOR\":5,\"LEADER\":3}},{\"text\":\"Find the fastest path to delivering real value, even imperfectly.\",\"clusterImpact\":{\"ENTREPRENEUR\":5,\"BUILDER\":3}},{\"text\":\"Explore creative angles others have not considered yet.\",\"clusterImpact\":{\"CREATOR\":5,\"ENTREPRENEUR\":3}},{\"text\":\"Identify who you need and build a support network around the goal.\",\"clusterImpact\":{\"LEADER\":5,\"CAREGIVER\":3}}]",
                            TestId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Text = "When handed a significant new responsibility, your first move is to..."
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000013"),
                            Code = "CF_13",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Order = 13,
                            QuestionType = 1,
                            ScenarioOptionsJson = "[{\"text\":\"Excited \\u2014 where there is risk, there is opportunity worth seizing.\",\"clusterImpact\":{\"ENTREPRENEUR\":5,\"CREATOR\":3}},{\"text\":\"Focused \\u2014 you model the downside and reduce it systematically.\",\"clusterImpact\":{\"ANALYST\":5,\"OPERATOR\":4}},{\"text\":\"Responsible \\u2014 your priority is protecting the people involved.\",\"clusterImpact\":{\"CAREGIVER\":5,\"LEADER\":2}},{\"text\":\"Curious \\u2014 you see it as a creative problem waiting to be reframed.\",\"clusterImpact\":{\"CREATOR\":5,\"ENTREPRENEUR\":2}}]",
                            TestId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Text = "Risk and uncertainty at work make you feel..."
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000014"),
                            Code = "CF_14",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Order = 14,
                            QuestionType = 1,
                            ScenarioOptionsJson = "[{\"text\":\"Pair up with them to debug or solve the technical challenge together.\",\"clusterImpact\":{\"BUILDER\":5,\"ANALYST\":3}},{\"text\":\"Sit with them, listen deeply, and offer genuine emotional support.\",\"clusterImpact\":{\"CAREGIVER\":5,\"COMMUNICATOR\":3}},{\"text\":\"Connect them to someone better positioned to help solve the problem.\",\"clusterImpact\":{\"COMMUNICATOR\":5,\"LEADER\":3}},{\"text\":\"Step in, take ownership of the situation, and drive it to resolution.\",\"clusterImpact\":{\"LEADER\":5,\"ENTREPRENEUR\":3}}]",
                            TestId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Text = "A colleague is visibly struggling with a tough assignment. You..."
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000015"),
                            Code = "CF_15",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Order = 15,
                            QuestionType = 1,
                            ScenarioOptionsJson = "[{\"text\":\"New product roadmap, engineering milestones, and technical innovations.\",\"clusterImpact\":{\"BUILDER\":5,\"ANALYST\":3}},{\"text\":\"Bold business growth targets and how the company plans to win the market.\",\"clusterImpact\":{\"ENTREPRENEUR\":5,\"ANALYST\":2}},{\"text\":\"Stories about employees or customers whose lives have been genuinely changed.\",\"clusterImpact\":{\"CAREGIVER\":5,\"COMMUNICATOR\":4}},{\"text\":\"Daring creative campaigns or brand moves that nobody saw coming.\",\"clusterImpact\":{\"CREATOR\":5,\"COMMUNICATOR\":3}}]",
                            TestId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Text = "At a company all-hands, you get most excited when you hear about..."
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000016"),
                            Code = "CF_16",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Order = 16,
                            QuestionType = 1,
                            ScenarioOptionsJson = "[{\"text\":\"Deep solo focus \\u2014 no meetings, no interruptions, just you and the problem.\",\"clusterImpact\":{\"ANALYST\":5,\"BUILDER\":4}},{\"text\":\"Fast-paced cross-functional sprints where you juggle multiple moving parts.\",\"clusterImpact\":{\"ENTREPRENEUR\":5,\"COMMUNICATOR\":3}},{\"text\":\"Clear structures, accountable teams, and well-defined repeatable processes.\",\"clusterImpact\":{\"OPERATOR\":5,\"LEADER\":3}},{\"text\":\"Open, diverse collaboration where great ideas can come from anywhere.\",\"clusterImpact\":{\"CREATOR\":5,\"COMMUNICATOR\":4}}]",
                            TestId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Text = "The work setup where you consistently do your absolute best is..."
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000017"),
                            Code = "CF_17",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Order = 17,
                            QuestionType = 1,
                            ScenarioOptionsJson = "[{\"text\":\"Having built products, tools, or infrastructure that millions depend on.\",\"clusterImpact\":{\"BUILDER\":5,\"ENTREPRENEUR\":2}},{\"text\":\"Running your own company, fund, or investment portfolio.\",\"clusterImpact\":{\"ENTREPRENEUR\":5,\"LEADER\":3}},{\"text\":\"Leading a large organisation or a mission-driven institution.\",\"clusterImpact\":{\"LEADER\":5,\"OPERATOR\":3}},{\"text\":\"Being recognised as the world\\u0027s leading expert in your field.\",\"clusterImpact\":{\"ANALYST\":5,\"COMMUNICATOR\":3}}]",
                            TestId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Text = "Looking further ahead, you would feel most fulfilled if your career led to..."
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000018"),
                            Code = "CF_18",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Order = 18,
                            QuestionType = 1,
                            ScenarioOptionsJson = "[{\"text\":\"What you built, shipped, or delivered that still runs reliably today.\",\"clusterImpact\":{\"BUILDER\":5,\"OPERATOR\":4}},{\"text\":\"The growth in revenue, users, or market share you personally drove.\",\"clusterImpact\":{\"ENTREPRENEUR\":5,\"ANALYST\":2}},{\"text\":\"The lives you changed or the problems you permanently solved for people.\",\"clusterImpact\":{\"CAREGIVER\":5,\"COMMUNICATOR\":3}},{\"text\":\"The new ideas, categories, or experiences you introduced to the world.\",\"clusterImpact\":{\"CREATOR\":5,\"ENTREPRENEUR\":3}}]",
                            TestId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Text = "At the end of it all, you measure success by..."
                        });
                });

            modelBuilder.Entity("MindScorePlatform.Domain.Entities.Report", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdatutc");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("userid");

                    b.HasKey("Id");

                    b.ToTable("reports", (string)null);
                });

            modelBuilder.Entity("MindScorePlatform.Domain.Entities.Response", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdatutc");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("questionid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("userid");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "QuestionId")
                        .IsUnique()
                        .HasDatabaseName("IX_Responses_UserId_QuestionId");

                    b.ToTable("responses", (string)null);
                });

            modelBuilder.Entity("MindScorePlatform.Domain.Entities.Result", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AdaptivePathJson")
                        .HasColumnType("text")
                        .HasColumnName("adaptivepathjson");

                    b.Property<string>("AiFollowUpJson")
                        .HasColumnType("text")
                        .HasColumnName("aifollowupjson");

                    b.Property<int>("Context")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("context");

                    b.Property<string>("ContextInsightsJson")
                        .HasColumnType("text")
                        .HasColumnName("contextinsightsjson");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdatutc");

                    b.Property<string>("DimensionConfidenceJson")
                        .HasColumnType("text")
                        .HasColumnName("dimensionconfidencejson");

                    b.Property<string>("DimensionScoresJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("dimensionscoresjson");

                    b.Property<string>("InsightsJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("insightsjson");

                    b.Property<string>("PersonalityEmoji")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("personalityemoji");

                    b.Property<string>("PersonalityName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("personalityname");

                    b.Property<string>("PersonalityTagline")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("personalitytagline");

                    b.Property<string>("PersonalityType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("personalitytype");

                    b.Property<decimal>("Score")
                        .HasColumnType("numeric")
                        .HasColumnName("score");

                    b.Property<Guid>("TestId")
                        .HasColumnType("uuid")
                        .HasColumnName("testid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("userid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "TestId")
                        .IsUnique()
                        .HasDatabaseName("IX_Results_UserId_TestId");

                    b.ToTable("results", (string)null);
                });

            modelBuilder.Entity("MindScorePlatform.Domain.Entities.Test", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdatutc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("tests", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "MindType Assessment"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Career Fit Assessment"
                        });
                });

            modelBuilder.Entity("MindScorePlatform.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AgeBandId")
                        .HasColumnType("uuid")
                        .HasColumnName("agebandid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdatutc");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dateofbirth");

                    b.Property<string>("Domicile")
                        .HasColumnType("text")
                        .HasColumnName("domicile");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<bool>("IsGuest")
                        .HasColumnType("boolean")
                        .HasColumnName("isguest");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("passwordhash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.HasKey("Id");

                    b.HasIndex("AgeBandId");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_Email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("MindScorePlatform.Domain.Entities.AgeBandModuleWeight", b =>
                {
                    b.HasOne("MindScorePlatform.Domain.Entities.AgeBand", "AgeBand")
                        .WithMany()
                        .HasForeignKey("AgeBandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MindScorePlatform.Domain.Entities.Module", "Module")
                        .WithMany()
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AgeBand");

                    b.Navigation("Module");
                });

            modelBuilder.Entity("MindScorePlatform.Domain.Entities.ModuleScore", b =>
                {
                    b.HasOne("MindScorePlatform.Domain.Entities.Module", "Module")
                        .WithMany("ModuleScores")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Module");
                });

            modelBuilder.Entity("MindScorePlatform.Domain.Entities.NormReference", b =>
                {
                    b.HasOne("MindScorePlatform.Domain.Entities.AgeBand", "AgeBand")
                        .WithMany()
                        .HasForeignKey("AgeBandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MindScorePlatform.Domain.Entities.Module", "Module")
                        .WithMany()
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AgeBand");

                    b.Navigation("Module");
                });

            modelBuilder.Entity("MindScorePlatform.Domain.Entities.Question", b =>
                {
                    b.HasOne("MindScorePlatform.Domain.Entities.AgeBand", "AgeBand")
                        .WithMany("Questions")
                        .HasForeignKey("AgeBandId");

                    b.HasOne("MindScorePlatform.Domain.Entities.Module", "Module")
                        .WithMany("Questions")
                        .HasForeignKey("ModuleId");

                    b.Navigation("AgeBand");

                    b.Navigation("Module");
                });

            modelBuilder.Entity("MindScorePlatform.Domain.Entities.User", b =>
                {
                    b.HasOne("MindScorePlatform.Domain.Entities.AgeBand", "AgeBand")
                        .WithMany()
                        .HasForeignKey("AgeBandId");

                    b.Navigation("AgeBand");
                });

            modelBuilder.Entity("MindScorePlatform.Domain.Entities.AgeBand", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("MindScorePlatform.Domain.Entities.Module", b =>
                {
                    b.Navigation("ModuleScores");

                    b.Navigation("Questions");
                });
#pragma warning restore 612, 618
        }
    }
}
