// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MindScorePlatform.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MindScorePlatform.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MindScorePlatform.Domain.Entities.AgeBand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("displayorder");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("isactive");

                    b.Property<int>("MaxAge")
                        .HasColumnType("integer")
                        .HasColumnName("maxage");

                    b.Property<int>("MinAge")
                        .HasColumnType("integer")
                        .HasColumnName("minage");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("agebands");
                });

            modelBuilder.Entity("MindScorePlatform.Domain.Entities.AgeBandModuleWeight", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AgeBandId")
                        .HasColumnType("uuid")
                        .HasColumnName("agebandid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<Guid>("ModuleId")
                        .HasColumnType("uuid")
                        .HasColumnName("moduleid");

                    b.Property<double>("Weight")
                        .HasColumnType("double precision")
                        .HasColumnName("weight");

                    b.HasKey("Id");

                    b.HasIndex("AgeBandId")
                        .HasDatabaseName("IX_agebandmoduleweights_agebandid");

                    b.HasIndex("ModuleId")
                        .HasDatabaseName("IX_agebandmoduleweights_moduleid");

                    b.ToTable("agebandmoduleweights");
                });

            modelBuilder.Entity("MindScorePlatform.Domain.Entities.Module", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("displayorder");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("isactive");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("modules");
                });

            modelBuilder.Entity("MindScorePlatform.Domain.Entities.ModuleScore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<Guid>("ModuleId")
                        .HasColumnType("uuid")
                        .HasColumnName("moduleid");

                    b.Property<decimal>("Percentile")
                        .HasColumnType("numeric")
                        .HasColumnName("percentile");

                    b.Property<decimal>("RawScore")
                        .HasColumnType("numeric")
                        .HasColumnName("rawscore");

                    b.Property<Guid>("TestId")
                        .HasColumnType("uuid")
                        .HasColumnName("testid");

                    b.Property<decimal>("WeightedScore")
                        .HasColumnType("numeric")
                        .HasColumnName("weightedscore");

                    b.HasKey("Id");

                    b.HasIndex("ModuleId")
                        .HasDatabaseName("IX_modulescores_moduleid");

                    b.ToTable("modulescores");
                });

            modelBuilder.Entity("MindScorePlatform.Domain.Entities.NormReference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AgeBandId")
                        .HasColumnType("uuid")
                        .HasColumnName("agebandid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<double>("Mean")
                        .HasColumnType("double precision")
                        .HasColumnName("mean");

                    b.Property<Guid>("ModuleId")
                        .HasColumnType("uuid")
                        .HasColumnName("moduleid");

                    b.Property<int>("SampleSize")
                        .HasColumnType("integer")
                        .HasColumnName("samplesize");

                    b.Property<double>("StandardDeviation")
                        .HasColumnType("double precision")
                        .HasColumnName("standarddeviation");

                    b.HasKey("Id");

                    b.HasIndex("AgeBandId")
                        .HasDatabaseName("IX_normreferences_agebandid");

                    b.HasIndex("ModuleId")
                        .HasDatabaseName("IX_normreferences_moduleid");

                    b.ToTable("normreferences");
                });

            modelBuilder.Entity("MindScorePlatform.Domain.Entities.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AgeBandId")
                        .HasColumnType("uuid")
                        .HasColumnName("agebandid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdatutc");

                    b.Property<string>("Difficulty")
                        .HasColumnType("text")
                        .HasColumnName("difficulty");

                    b.Property<bool?>("IsReverseScored")
                        .HasColumnType("boolean")
                        .HasColumnName("isreversescored");

                    b.Property<Guid?>("ModuleId")
                        .HasColumnType("uuid")
                        .HasColumnName("moduleid");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("orderid");

                    b.Property<Guid>("TestId")
                        .HasColumnType("uuid")
                        .HasColumnName("testid");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.Property<int?>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("numeric")
                        .HasColumnName("weight");

                    b.HasKey("Id");

                    b.HasIndex("AgeBandId")
                        .HasDatabaseName("IX_Questions_agebandid");

                    b.HasIndex("ModuleId")
                        .HasDatabaseName("IX_Questions_moduleid");

                    b.HasIndex("TestId", "Code")
                        .IsUnique()
                        .HasDatabaseName("IX_Questions_TestId_Code");

                    b.HasIndex("TestId", "Order")
                        .IsUnique()
                        .HasDatabaseName("IX_Questions_TestId_Order");

                    b.ToTable("questions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000001"),
                            Code = "EI_01",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Order = 1,
                            TestId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Text = "I feel energised after spending time with friends or a group of people."
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000002"),
                            Code = "EI_02_R",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Order = 2,
                            TestId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Text = "After a busy social day, I need quiet time alone to feel like myself again."
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000003"),
                            Code = "EI_03",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Order = 3,
                            TestId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Text = "I enjoy starting conversations with people I've never met before."
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000004"),
                            Code = "EI_04_R",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Order = 4,
                            TestId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Text = "I find large gatherings draining, even when I enjoy the people there."
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000005"),
                            Code = "EI_05",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Order = 5,
                            TestId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Text = "I think better when I'm talking ideas through with someone rather than sitting with them alone."
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000006"),
                            Code = "SN_01",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Order = 6,
                            TestId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Text = "I prefer clear, step-by-step instructions over figuring things out as I go."
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000007"),
                            Code = "SN_02_R",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Order = 7,
                            TestId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Text = "I often find myself thinking about what could be, more than what currently is."
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000008"),
                            Code = "SN_03",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Order = 8,
                            TestId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Text = "I trust facts and direct experience more than gut feelings or hunches."
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000009"),
                            Code = "SN_04_R",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Order = 9,
                            TestId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Text = "I get excited by new ideas and possibilities, even when they're not fully formed yet."
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000010"),
                            Code = "SN_05",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Order = 10,
                            TestId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Text = "I focus on the task at hand rather than getting distracted by future possibilities."
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000011"),
                            Code = "TF_01",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Order = 11,
                            TestId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Text = "When solving a problem, I focus on what's logical and objective rather than what feels right."
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000012"),
                            Code = "TF_02_R",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Order = 12,
                            TestId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Text = "I find it difficult to make a decision if I know it will upset someone close to me."
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000013"),
                            Code = "TF_03",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Order = 13,
                            TestId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Text = "I believe being fair and consistent matters more than making exceptions for individuals."
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000014"),
                            Code = "TF_04_R",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Order = 14,
                            TestId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Text = "I consider how my decisions will affect the feelings of the people involved."
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000015"),
                            Code = "TF_05",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Order = 15,
                            TestId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Text = "I prefer a well-reasoned argument over an emotional appeal when making up my mind."
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000016"),
                            Code = "JP_01",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Order = 16,
                            TestId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Text = "I like having a clear plan before I start a task."
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000017"),
                            Code = "JP_02_R",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Order = 17,
                            TestId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Text = "I prefer to keep my options open rather than committing to a fixed plan."
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000018"),
                            Code = "JP_03",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Order = 18,
                            TestId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Text = "I feel unsettled when plans change unexpectedly at the last minute."
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000019"),
                            Code = "JP_04_R",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Order = 19,
                            TestId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Text = "I often decide things at the last moment and feel perfectly comfortable doing so."
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000020"),
                            Code = "JP_05",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Order = 20,
                            TestId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Text = "I prefer to have things resolved and settled rather than leaving them open-ended."
                        });
                });

            modelBuilder.Entity("MindScorePlatform.Domain.Entities.Report", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdatutc");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("userid");

                    b.HasKey("Id");

                    b.ToTable("reports");
                });

            modelBuilder.Entity("MindScorePlatform.Domain.Entities.Response", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdatutc");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("questionid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("userid");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "QuestionId")
                        .IsUnique()
                        .HasDatabaseName("IX_Responses_UserId_QuestionId");

                    b.ToTable("responses");
                });

            modelBuilder.Entity("MindScorePlatform.Domain.Entities.Result", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdatutc");

                    b.Property<string>("DimensionScoresJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("dimensionscoresjson");

                    b.Property<string>("InsightsJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("insightsjson");

                    b.Property<string>("PersonalityEmoji")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("personalityemoji");

                    b.Property<string>("PersonalityName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("personalityname");

                    b.Property<string>("PersonalityTagline")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("personalitytagline");

                    b.Property<string>("PersonalityType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("personalitytype");

                    b.Property<decimal>("Score")
                        .HasColumnType("numeric")
                        .HasColumnName("score");

                    b.Property<Guid>("TestId")
                        .HasColumnType("uuid")
                        .HasColumnName("testid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("userid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "TestId")
                        .IsUnique()
                        .HasDatabaseName("IX_Results_UserId_TestId");

                    b.ToTable("results");
                });

            modelBuilder.Entity("MindScorePlatform.Domain.Entities.Test", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdatutc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("tests");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "MindType Assessment"
                        });
                });

            modelBuilder.Entity("MindScorePlatform.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AgeBandId")
                        .HasColumnType("uuid")
                        .HasColumnName("agebandid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdatutc");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dateofbirth");

                    b.Property<string>("Domicile")
                        .HasColumnType("text")
                        .HasColumnName("domicile");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<bool>("IsGuest")
                        .HasColumnType("boolean")
                        .HasColumnName("isguest");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("passwordhash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.HasKey("Id");

                    b.HasIndex("AgeBandId")
                        .HasDatabaseName("IX_Users_agebandid");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_Email");

                    b.ToTable("users");
                });

            modelBuilder.Entity("MindScorePlatform.Domain.Entities.AgeBandModuleWeight", b =>
                {
                    b.HasOne("MindScorePlatform.Domain.Entities.AgeBand", "AgeBand")
                        .WithMany()
                        .HasForeignKey("AgeBandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MindScorePlatform.Domain.Entities.Module", "Module")
                        .WithMany()
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AgeBand");
                    b.Navigation("Module");
                });

            modelBuilder.Entity("MindScorePlatform.Domain.Entities.ModuleScore", b =>
                {
                    b.HasOne("MindScorePlatform.Domain.Entities.Module", "Module")
                        .WithMany("ModuleScores")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Module");
                });

            modelBuilder.Entity("MindScorePlatform.Domain.Entities.NormReference", b =>
                {
                    b.HasOne("MindScorePlatform.Domain.Entities.AgeBand", "AgeBand")
                        .WithMany()
                        .HasForeignKey("AgeBandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MindScorePlatform.Domain.Entities.Module", "Module")
                        .WithMany()
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AgeBand");
                    b.Navigation("Module");
                });

            modelBuilder.Entity("MindScorePlatform.Domain.Entities.Question", b =>
                {
                    b.HasOne("MindScorePlatform.Domain.Entities.AgeBand", "AgeBand")
                        .WithMany("Questions")
                        .HasForeignKey("AgeBandId");

                    b.HasOne("MindScorePlatform.Domain.Entities.Module", "Module")
                        .WithMany("Questions")
                        .HasForeignKey("ModuleId");

                    b.Navigation("AgeBand");
                    b.Navigation("Module");
                });

            modelBuilder.Entity("MindScorePlatform.Domain.Entities.User", b =>
                {
                    b.HasOne("MindScorePlatform.Domain.Entities.AgeBand", "AgeBand")
                        .WithMany()
                        .HasForeignKey("AgeBandId");

                    b.Navigation("AgeBand");
                });
#pragma warning restore 612, 618
        }
    }
}
